# tasks file
---

- name: Create fonts directory
  become: true
  file:
    path: "{{ fonts_path }}"
    mode: '0755'
    state: directory

- name: Copy powerlevel10k recommanded fonts
  become: true
  copy:
    src: "fonts/{{ item }}"
    dest: "{{ fonts_path }}/{{ item }}"
    mode: '0644'
  loop:
    - MesloLGS NF Bold Italic.ttf
    - MesloLGS NF Bold.ttf
    - MesloLGS NF Italic.ttf
    - MesloLGS NF Regular.ttf

- name: ensure fonts directory
  file:
    path: "{{ fonts_path }}"
    state: directory

- name: Update apt cache
  apt:
    update_cache: yes

- name: install packages
  package:
    name:
      - htop
      - ranger
      - bat
      - tmux
      - git
      - zsh
      - picocom
      - minicom
      - ssh
      - tree
      - rsync
      - iperf3
      - build-essential
      - autoconf
      - bison
      - flex
      - texinfo
      - help2man
      - gawk
      - libtool-bin
      - libncurses5-dev
      - unzip
      - qemu-user
      - libssl-dev
      - device-tree-compiler
      - swig
      - bridge-utils
      - net-tools
      - nfs-kernel-server
      - uml-utilities
      - rlwrap
      - curl
      - xsel
      - fzf
      - peco
      - fzy
      - fd-find
      - ripgrep
    autoclean: yes

- name: install python packages
  package:
    name:
      - python3
      - python3-distutils
      - python3-dev
      - python3-setuptools
      - python3-pip
    autoclean: yes

- name: Install virtualenv
  pip:
    name: virtualenv
    state: latest
    executable: pip3

- name: clone oh-my-zsh for user
  tags:
    # Suppress warning: [ANSIBLE0006] git used in place of git module
    # Git module doesn't allow us to set `core.autocrlf=input`.
    - skip_ansible_lint
  become: yes
  become_user: "{{ username }}"
  git:
    repo: "https://github.com/ohmyzsh/ohmyzsh.git"
    dest: "~{{ username }}/.oh-my-zsh"

- name: clone powerlevel10k for userss
  become: yes
  become_user: '{{ username }}'
  git:
    repo: 'https://github.com/romkatv/powerlevel10k.git'
    version: master
    dest: "~{{ username }}/.oh-my-zsh/custom/themes/powerlevel10k"

- name: clone zsh-autosuggestions for users
  become: yes
  become_user: '{{ username }}'
  git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    version: master
    dest: '~{{ username }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions'

- name: clone forgit for users
  become: yes
  become_user: '{{ username }}'
  git:
    repo: 'https://github.com/wfxr/forgit.git'
    version: master
    dest: '~{{ username }}/.oh-my-zsh/custom/plugins/forgit'

- name: clone syntax highlighting  for users
  become: yes
  become_user: '{{ username }}'
  git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    version: master
    dest: '~{{ username }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting'

- name: clone enhancd for users
  become: yes
  become_user: '{{ username }}'
  git:
    repo: 'https://github.com/b4b4r07/enhancd.git'
    version: master
    dest: '~{{ username }}/.oh-my-zsh/custom/plugins/enhancd'

- name: write .p10k.zsh for users
  become: yes
  become_user: '{{ username }}'
  template:
    src: p10k.zsh.j2
    dest: ~{{ username }}/.p10k.zsh
    backup: yes
    mode: 'u=rw,go=r'

- name: write .zshrc for user
  become: yes
  become_user: "{{ username }}"
  template:
    src: zshrc.j2
    dest: "~{{ username }}/.zshrc"
    backup: yes
    mode: "u=rw,go=r"

- name: set default shell for users
  become: yes
  user:
    name: '{{ username }}'
    shell: /bin/zsh

- name: Clone TPM repository
  become: yes
  become_user: "{{ username }}"
  git:
    repo: "https://github.com/tmux-plugins/tpm.git"
    dest: "~{{ username }}/.tmux/plugins/tpm"

- name: write .tmux.conf for user
  become: yes
  become_user: "{{ username }}"
  template:
    src: tmux.conf.j2
    dest: "~{{ username }}/.tmux.conf"
    backup: yes
    mode: "u=rw,go=r"

- name: clone embedded-qemu-labs
  become: yes
  become_user: '{{ username }}'
  git:
    repo: 'git@github.com:dooraim/embedded-qemu-labs.git'
    version: master
    dest: '~{{ username }}/git@github.com:dooraim/embedded-qemu-labs.git'

- name: clone crosstool-ng
  become: yes
  become_user: '{{ username }}'
  git:
    repo: 'https://github.com/crosstool-ng/crosstool-ng'
    version: master
    dest: '~{{ username }}/embedded-qemu-labs/toolchain/'

- name: Download Installer cht.sh
  get_url:
    url: https://cht.sh/cht.sh
    dest: /bin/cht.sh
    mode: '0755'
    force: 'yes'

- name: Install NEOVIM - >=O.9
  community.general.snap:
    name: nvim
    classic: yes

- name: Clone LazyVim starter
  git:
    repo: https://github.com/LazyVim/starter
    dest: ~{{ username }}/.config/nvim
    update: yes
  become: yes
  become_user: '{{ username }}'

- name: Remove .git directory from ~/.config/nvim
  file:
    path: ~{{ username }}/.config/nvim/.git
    state: absent
  become: yes
  become_user: '{{ username }}'

- name: Clone the Git repository
  git:
    repo: https://gitlab.com/phoneybadger/pokemon-colorscripts.git
    dest: ~{{ username }}/pokemon-colorscripts
    version: main
  become_user: '{{ username }}'

- name: Run the install script
  command: ./install.sh
  args:
    chdir: ~{{ username }}/pokemon-colorscripts
  become: yes

- name: Remove the pokemon-colorscripts directory
  file:
    path: ~{{ username }}/pokemon-colorscripts
    state: absent
  become_user: '{{ username }}'
